### ISSUE TITLE
公众号段落间距

### ISSUE THREAD

**Issue by thend03** [caol64/wenyan#33]
最近在看文章样式的时候，发现文字比较多的情况下，段落间距不是很大，导致看起来没有那么美观

如下图片是我发表的文章效果
<img width="865" alt="Image" src="https://github.com/user-attachments/assets/273626ce-c417-4335-855c-01120981090e" />

这个是我看半佛仙人的文章
<img width="950" alt="Image" src="https://github.com/user-attachments/assets/b7cd5b7c-e32f-44fb-8626-68c096950b94" />

我在浏览器看了2篇文章的字体样式，font-size都是16px，但是半佛文章的段落间距和字体看起来都比我的文章的效果更好，感觉更加舒服一点

期待可以调一下段落间距和样式

**Comment by caol64** [comment]
你可以试着设置一个自定义主题，比如要设置段落间距可以添加下面的内容：

```css
#wenyan p {
    padding: 0.5em 0; /* 或者把em改成px */
}
```

同样的字体也可以这样设置。
